name: Styra GitHub Actions Demo
on: [push]
jobs:
  validate_kubernetes_manifests:
    runs-on: ubuntu-latest
    env:
      STYRA_ORGANIZATION_ID: sullivan.styra.com
      STYRA_TOKEN: ${{ secrets.STYRA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Download Styra CLI
        run: |
          curl -s -o styra https://docs.styra.com/bin/linux/amd64/styra
          mv styra /usr/local/bin/styra
          chmod +x /usr/local/bin/styra
      - name: Run Styra Validate Check Local
        run: |
          styra validate check-local
